### PR TITLE
Ubuntu 16.04 fixes

### PR DESCRIPTION
**Pull request by paboldin**
Fix tests on Ubuntu 16.04.

Signed-off-by: Pavel Boldin <boldin.pavel@gmail.com>

### CODE REVIEW

**Comment by skinsbursky** [comment]
Hi, Pavel!
The first one was merged. Thanks!
But I have a couple of questions about the second one.
How we can have binaries without .rela.plt and .rela.dyn? Special compilation options?

**Comment by paboldin** [comment]
Both .rela.dyn and .rela.plt are optional. Linker won't generate them if there is no need.
-------------------
$ cat libtest.c 
#include <stdio.h>

int foobar()
{
	printf("abc\n");
}
$ gcc -shared -o libtest.so libtest.c -fPIC -nostdlib
$ readelf -SW libtest.so  | grep RELA
  [ 5] .rela.plt         RELA            00000000000002f8 0002f8 000018 18  AI  3  12  8



-------------------------
$ cat libtest.c 
#include <stdio.h>

int foobar()
{
	stdout = 0;
}
$ gcc -shared -o libtest.so libtest.c -fPIC -nostdlib
$ readelf -SW libtest.so  | grep RELA
  [ 5] .rela.dyn         RELA            00000000000002f8 0002f8 000018 18   A  3   0  8

**Comment by skinsbursky** [comment]
So, it's support for binaries not linked with stdlib. Fair enough.
Never tried it as well though.
So, you tried such a patch build with "-nostdlib"?
Does it work?

**Comment by paboldin** [comment]
Second example will not generate .rela.plt even without nostdlib option.

No, i have not tried it.

17 июля 2017 г. 2:13 PM пользователь "Stanislav Kinsburskii" <
notifications@github.com> написал:

**Comment by skinsbursky** [comment]
Ok, got it.
Merged you fixes (although split them into few patches).
Thanks!

**Pull request merged**
